<?php

/**
 * Module file for Wilke popup.
 */

/**
 * Implements hook_menu().
 */
function wilke_popup_menu() {
  $items = array();

  $items['admin/config/ding/wilke-popup'] = array(
    'title' => 'Wilke popup',
    'description' => 'Change the Wilke popup text',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wilke_popup_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );

  $items['wilke-popup'] = array(
    'page callback' => 'wilke_popup_callback',
    'delivery callback' => 'ajax_deliver',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Ajax callback to render the popup.
 */
function wilke_popup_callback() {
  $commands = array();

  // Use some basic XSS protection while still allowing tags.
  $html = filter_xss_admin(variable_get('wilke_popup_text', ''));
  $html .= l(t('No thanks'), '<front>', array(
    'attributes' => array(
      'class' => array('action-button', 'bookmark-button'),
      'style' => 'margin-right:10px;',
    ),
  ));
  $html .= l(t('Yes please'), 'http://survey4.wilkeonline.com/entry.aspx?ssid=6371-98751&lan=da', array(
    'attributes' => array(
      'class' => array('action-button', 'bookmark-button'),
      'target' => '_blank',
    ),
  ));
  $html .= '<br>';

  $commands[] = ajax_command_ding_popup('ding_bookmark', t('Sorry to interrupt'), $html);

  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * Form builder callback for wilke admin settings form.
 */
function wilke_popup_admin_settings($form, &$form_state) {
  $form['wilke_popup_text'] = array(
    '#type' => 'textarea',
    '#title' => t('Wilke popup text'),
    '#description' => t('Enter the text to show in the Wilke popup (some tags allowed).'),
    '#default_value' => variable_get('wilke_popup_text', ''),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_page_build().
 */
function wilke_popup_page_build(&$page) {
  if (drupal_is_front_page()) {
    drupal_add_library('system', 'drupal.ajax');
    drupal_add_js(drupal_get_path('module', 'ding_facetbrowser') . '/js/jquery.cookie.min.js');
    drupal_add_js(drupal_get_path('module', 'wilke_popup') . '/wilke_popup.js');
    $page['page_bottom']['wilke_popup']['#markup'] = l('', 'wilke-popup', array(
      'attributes' => array(
        'style' => 'display:none;',
        'id' => 'wilke-popup',
        'class' => 'use-ajax',
      ),
    ));
  }
}
